name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel==0.43.0 twine==6.0.1 packaging==24.1 pkginfo==1.12.0

#    - name: Run examples
#      env:
#        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
#      run: |
#        python examples/core/score.py
#        python examples/custom/sdk_custom_rule.py
#        python examples/llm_and_rule/llm_and_rule_mix.py
#        python examples/register/sdk_register_llm.py
#        python examples/register/sdk_register_prompt.py
#        python examples/register/sdk_register_rule.py
#        python examples/multi_turn_dialogues/sdk_mtbench101_llm.py
#        python examples/multi_turn_dialogues/sdk_mtbench101_rule_all.py

    - name: Build package
      run: python setup.py bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
